# Generated by Django 4.0.2 on 2022-02-19 14:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhanr', models.CharField(max_length=100000)),
                ('nameBook', models.CharField(max_length=100000)),
                ('nameAutor', models.CharField(max_length=100000)),
                ('shortText', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photoBook', models.ImageField(blank=True, default=0, null=True, upload_to='books')),
                ('fileBook', models.FileField(blank=True, default=0, null=True, upload_to='booksFile')),
                ('field_name', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='internationalCooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100000)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default=0, null=True, upload_to='internationalCooperation')),
                ('field_name', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'МЕЖДУНАРОДНОЕ СОТРУДНИЧЕСТВО',
                'verbose_name_plural': 'МЕЖДУНАРОДНОЕ СОТРУДНИЧЕСТВО',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100000)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default=0, null=True, upload_to='news')),
                ('field_name', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='news_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100000)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default=0, null=True, upload_to='news_out')),
                ('field_name', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Зарубежны Новость',
                'verbose_name_plural': 'Зарубежные Новости',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(max_length=100000)),
                ('information', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default=0, null=True, upload_to='person')),
                ('field_name', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководство',
            },
        ),
        migrations.CreateModel(
            name='stati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100000)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default=0, null=True, upload_to='stati')),
                ('field_name', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статия',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='studentBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100000)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default=0, null=True, upload_to='studentHouse')),
                ('field_name', models.DateTimeField(auto_now_add=True)),
                ('course', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Дарынды студенттер',
                'verbose_name_plural': 'Дарынды студенттер',
            },
        ),
        migrations.CreateModel(
            name='studentHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100000)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default=0, null=True, upload_to='studentHouse')),
                ('field_name', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Студенттік жатахана',
                'verbose_name_plural': 'Студенттік жатахана',
            },
        ),
        migrations.CreateModel(
            name='studentLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100000)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default=0, null=True, upload_to='studentLive')),
                ('field_name', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Студенттік өмір',
                'verbose_name_plural': 'Студенттік өмір',
            },
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100000)),
                ('photo', models.ImageField(blank=True, default=0, null=True, upload_to='video')),
                ('url', models.CharField(max_length=100000)),
                ('field_name', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='youthWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100000)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default=0, null=True, upload_to='youthWork')),
                ('field_name', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Работа с молодёжью',
                'verbose_name_plural': 'Работа с молодёжью',
            },
        ),
    ]
