# Generated by Django 4.0.3 on 2022-03-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_studentbest_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbest',
            name='text',
        ),
        migrations.AddField(
            model_name='studentbest',
            name='name',
            field=models.CharField(default='real', max_length=100000),
        ),
        migrations.AlterField(
            model_name='studentbest',
            name='photo',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='studentBest_media'),
        ),
    ]
