# Generated by Django 4.0.3 on 2022-03-20 06:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_medresetecher'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100000)),
                ('email', models.CharField(max_length=100000)),
                ('type', models.DateTimeField(auto_now_add=True)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ұсыныс қалдыру',
                'verbose_name_plural': 'Ұсыныс қалдыру',
            },
        ),
        migrations.CreateModel(
            name='mainFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100000)),
                ('email', models.CharField(max_length=100000)),
                ('type', models.DateTimeField(auto_now_add=True)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Директорға сұрақ',
                'verbose_name_plural': 'Директорға сұрақ',
            },
        ),
    ]
