# Generated by Django 4.0.3 on 2022-03-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_feedback_mainfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='mainfeedback',
            name='type',
            field=models.CharField(max_length=100000),
        ),
    ]
