# Generated by Django 4.0.3 on 2022-03-29 17:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_feedback_type_alter_mainfeedback_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='bailanys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100000)),
                ('email', models.CharField(max_length=100000)),
                ('type', models.CharField(max_length=100000)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Байланыс',
                'verbose_name_plural': 'Байланыс',
            },
        ),
    ]
