# Generated by Django 4.0.3 on 2022-04-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_dayip_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='date',
        ),
    ]
