# Generated by Django 4.0.3 on 2022-04-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_dayip_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='date',
            field=models.CharField(max_length=100, verbose_name='date'),
        ),
    ]
